### ISSUE TITLE
Copy Paste from NumberFormat

### ISSUE THREAD

**Issue by vron** [dnbexperience/eufemia#1947]
In the documentation at https://eufemia.dnb.no/uilib/components/number-format/ it is specifically mentioned that the component should:

"To enhance the Copy & Paste experience of copying numbers into other applications, the NumberFormat component automatically changes the number formatting to be without thousand separators and to have a dot, instead of a comma for the decimal separator."

That is exactly the behaviour I want - allowing users to copy the numbers into Excel easily (in particualar I have a table of NumberFormats that should be copy-able to excel).

However - in practice the component does not seem to do this, neither when copying a single NumberFormat or a table of them.

To reproduce:
go to  https://eufemia.dnb.no/uilib/components/number-format/ and select+copy one of the examples (ctrl-C) and paste into notepad or excel and see that it's not pasted as a number.

**Comment by tujoworker** [comment]
Yeah! That's why I originally have made this enabled by default. But then several people thought it is "confusing". So we moved it behind a property called `clean_copy_value` in this [PR](https://github.com/dnbexperience/eufemia/pull/1065). But the docs got never updated. 

You can use the Provider, to enable this for all your NumberFormat components:

```jsx
import { Provider } from '@dnb/eufemia/shared'

<Provider value={{ NumberFormat: { clean_copy_value: true} }}>
  <NumberFormat
    currency
    value={-12345678.9}
    currency_display="code"
  />
</Provider>
```

I make a PR for fix the docs 👍 If you are OK with that behavior?

**Comment by vron** [comment]
Testing the property now :-)

**Comment by vron** [comment]
Does not seem to be working though? Have tried to update to latest (46.1) and still not getting the desired behaviour - neither with the provider nor using it as a fixed property on the components:

` 
<td><NumberFormat clean_copy_value={true} value={m / (deals[i].conversions.bpv ?? -1)} decimals={1} /></td>
<td><NumberFormat clean_copy_value={true} value={m} decimals={0} /></td>
<td><NumberFormat clean_copy_value={true} percent value={100 * r} decimals={1} /></td>
`

**Comment by tujoworker** [comment]
I sure we will figure out a good solution. 
I assume you get a coma when you copy the number? (I agree, we need to adjust this in the PR)

That's on purpose. Because we assume you have an Excel then that also wants a coma as the decimal separator. At least my Excel wants a coma (the number to the left):

<img width="537" alt="Screenshot 2023-01-26 at 08 48 11" src="https://user-images.githubusercontent.com/1501870/214783460-ca32150d-0daf-4863-b183-99c475649963.png">

When you set the locale to `en-GB` you should get a dot:

```jsx
<Provider locale="en-GB" value={{ NumberFormat: { clean_copy_value: true} }}>
  <NumberFormat
    currency
    value={-12345678.9}
    currency_display="code"
  />
</Provider>
```

Let me know what do you think we should an can do.

**Comment by vron** [comment]
Thanks for the input - I will try again during the day  (because yes I got the comma, but also the spaces and % signs - i.e. the flag seems to have no effect what so ever))

**Comment by tujoworker** [comment]
I added an example in the PR portal. Check out the [last example](https://eufemia-docsfixnumberformat.gatsbyjs.io/uilib/components/number-format/#using-the-provider-with-numberformat).

**Comment by tujoworker** [comment]
I think, we merge this docs change for now. And make a new PR if we find out we need more changes, either in the docs or in the component. Let me know how it works out for you 🙏
