### ISSUE TITLE
Field.PostalCodeAndCity in a Card gets a black border

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2893]
## 🐛 Bug Report

`Field.PostalCodeAndCity` while in a `Card` gets a black border:
<img width="732" alt="image" src="https://github.com/dnbexperience/eufemia/assets/1359205/a37d8afb-203e-4c84-8b80-c15ce2eb4a49">

## To Reproduce

https://codesandbox.io/s/funny-wilbur-p6zq8q?file=/src/App.tsx

https://codesandbox.io/s/jolly-blackburn-32p58l?file=/src/App.tsx

## Expected behavior

I expect the `Field.PostalCodeAndCity` to behave/look as much as the other `Field` components, which does not have black borders.

## Eufemia Version

 `10.13.0`

**Comment by tujoworker** [comment]
As of now, the forms styles need to be included in your CodeSandbox. 

Reason: In this case, its the internally used **FieldBlock** that uses a `fieldset` element, which creates this border (added by browsers). But the **FieldBlock** styles needs to be imported in order to "remove" the fieldset border.

```tsx
import '@dnb/eufemia/style'
import '@dnb/eufemia/extensions/forms/style'
```
