### ISSUE TITLE
bug(Field.PostalCodeAndCity): postalcode field doesn't display a red error border when error

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#2968]
## 🐛 Bug Report

`PostalCodeAndCity`'s postalcode field doesn't display a red error border when error

## To Reproduce

https://codesandbox.io/p/sandbox/empty-firefly-7ppx4n?file=%2Fsrc%2FApp.tsx

Type in `"1"` in the postal code field, and tab to the next field.
You'll be presented with an error message, but no red/error border around the postal code field, to indicate which field that causes the error. Looking [like](https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/PostalCodeAndCity/#error):
<img width="391" alt="image" src="https://github.com/dnbexperience/eufemia/assets/1359205/ef5753bb-1fdb-4319-aca9-9c4339f4fca5">

## Expected behavior

Reason for expecting a red/error border around the field that has the error is because all/most other `<Field.X />`-components behaves this way, having an error/red border, like:
- [NationalIdentityNumber](https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/NationalIdentityNumber/#error)
<img width="411" alt="Screenshot 2023-12-05 at 12 59 08" src="https://github.com/dnbexperience/eufemia/assets/1359205/58ed5038-8e95-46d9-8a02-a839efc3f9ad">

- [OrganizationNumber](https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/OrganizationNumber/#error)
<img width="370" alt="Screenshot 2023-12-05 at 12 59 01" src="https://github.com/dnbexperience/eufemia/assets/1359205/a8a3a0f6-3dbc-4633-98f0-3797617225a7">

- [Email](https://eufemia.dnb.no/uilib/extensions/forms/feature-fields/Email/#error-message)
<img width="378" alt="Screenshot 2023-12-05 at 12 59 16" src="https://github.com/dnbexperience/eufemia/assets/1359205/a57a8ce5-e32e-4fc6-a70b-b31a41b9a419">

**Comment by joakbjerk** [comment]
The culprit seems to be a check, inside the `useDataValue` hook, that sees if the component/hook is used inside a `FieldBlock` component, so any component inside a field block will not receive the red border-color on error. This affects the `PhoneNumber` component too. 

<img width="657" alt="Screenshot 2023-12-06 at 12 50 59" src="https://github.com/dnbexperience/eufemia/assets/25927156/3e0a18cb-e9c7-4a4a-bd73-8b92b9aecf31">

**Comment by snorrekim** [comment]
This has since been solved for some of the Field.Date and Field.String (https://github.com/dnbexperience/eufemia/pull/3081/files#diff-82c0dcb982ee31d1da123e9178b9a9b8a595e5278293b79374ebba6e3a35cbdb). But we will have to do so for all the Field types if we want to solve this issue for good.

And `hasError` is a bit of an odd name, it basically means, "this field has an error but you don't have an error message to show, so only add the red border". I think a better solution would be to either:

* Rename the `error` prop to `errorMessage`, and make `hasError` the main property used for deciding visuals.
* Send in an empty string as error to activate the styling, but not show a message
* Send in the error, but change `hasError` to `isInFieldBlock` and let the Field handle the visuals based on that info
