### ISSUE TITLE
Deliver transpiled code alongside source in NPM package

### ISSUE THREAD

**Issue by PatrikRistrom** [dnbexperience/eufemia#551]
## 🚀 Feature Proposal

We should be able to install the module and use it without first transpiling it on our own

## Motivation

The primary motiviation is that is should simply work as most other NPM modules, which will make it integrate cleanly with all manner of different tools and packages.

Certain packages and frameworks expect NPM packages to be already built, and does not like it when you try to feed them non-transpiled code

For instance, when using Next.JS you have to use something like [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules) to make it work properly (as far as I know)

Testing also can become quite a huge pain, as some testing frameworks will not transpile packages that get imported

**Comment by tujoworker** [comment]
Thanks for the request! In order to support proper tree shaking out of the box (in most cases) without forcing every dev to import the parts with a special path etc. the `dnb-ui-lib` uses since a couple of versions ago `esm` as the default module format. ESM is the future and many will follow along. [Note.js v12](https://nodejs.org/en/blog/release/v12.17.0/) has just some weeks ago removed the `--experimental-modules` flag (it was there for years)  and Jest will [soon support esm](https://github.com/facebook/jest/issues/9430) out of the box as well.

So, because most devs in DNB uses environments that supports ESM, I think it was a good decision to move along one step in to the future already now.

But for sure,`cjs` is still supported, so you don't need to transpiling by yourself. You just need to import the components properly in order to lower the total bundle size.

You find more info about module formats and Jest/SSR support etc.: https://eufemia.dnb.no/uilib/usage/first-steps/module-formats

With this info, let me know your opinion ☺️

**Comment by tujoworker** [comment]
I just update the deps of the next.js example. You may have a look on that as well: https://github.com/dnbexperience/eufemia-examples/tree/master/packages/example-next

**Comment by PatrikRistrom** [comment]
Yes you can feel free to ignore this, if I would have actually looked closer on the documentation this wouldn't have been an issue 😅 

Thanks 👍
