### ISSUE TITLE
What's the difference between using on_click and onClick properties of the Button component?

### ISSUE THREAD

**Issue by langz** [dnbexperience/eufemia#683]
Hello 👋  

I've browsed through Eufemia UI Library for some inspiration, and came over the demos of the Button component.
https://eufemia.dnb.no/uilib/components/button/demos
In the demos, I can see that both ```on_click```, and ```onClick``` properties is used.
What's the difference? Does it matter which I use? Why do both need to exist?

I've looked for answers in https://eufemia.dnb.no/uilib/components/button/properties and in https://eufemia.dnb.no/uilib/development/naming#why-snake_case-property-naming, but couldn't seem to find answers there.

**Comment by tujoworker** [comment]
Hi Anders!

thank you for the question. There is no differance. As of now, we use snake case for properties (and events), because of Web Components support. But recenly DNB has decided to go for React as their stack, and that means we can favor React spessifik conventions. So probably we will go for camel case in near future.
